# 선문대학교 컴퓨터공학부
# 2022243101 최완우

# **4. 선형회귀와 지도학습**
---
* 출판사 : 생능 출판사( http://www.booksr.co.kr/ )
* 으뜸 머신러닝 저자 : 강영민, 박동규, 김성수
*  소스코드 저장소 : https://github.com/dknife/ML2nd
*  저작권 : 본 노트북 코드는 자유롭게 배포가능하지만 위의 출판사, 저서, 저자표기와 함께 배포해 주십시오.
---

### 5.6 사이킷 런의 성능지표 함수들

In [1]:
import numpy as np
target = np.array([0] * 10 + [1] * 10)
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [2]:
pred = np.array([0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1])
pred

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1])

In [3]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target, pred)

array([[7, 3],
       [2, 8]])

In [5]:
from sklearn.metrics import precision_score, recall_score
print('정밀도 : ', precision_score(target, pred))
print('재현율 : ', recall_score(target, pred))

from sklearn.metrics import accuracy_score, f1_score
print('정확도 : ', accuracy_score(target, pred))
print('F1 점수 : ', f1_score(target, pred))

정밀도 :  0.7272727272727273
재현율 :  0.8
정확도 :  0.75
F1 점수 :  0.7619047619047619
